[pytest]
testpaths = tests/unit
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning:websockets.legacy.*:
    ignore:websockets.server.WebSocketServerProtocol is deprecated:DeprecationWarning
    ignore:remove second argument of ws_handler:DeprecationWarning
