"""SGF (Smart Game Format) utilities for Light-Go.

This module provides utilities for generating SGF files from self-play games,
including proper metadata handling and standardized file naming.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional, TYPE_CHECKING

from sgfmill import sgf

if TYPE_CHECKING:
    from core.self_play import GameResult

logger = logging.getLogger(__name__)


def create_sgf_from_game_result(
    game_result: GameResult,
    board_size: int = 19,
    komi: float = 7.5,
    num_simulations: Optional[int] = None,
    temperature_threshold: Optional[int] = None,
    player_name: str = "Light-Go Self-Play"
) -> sgf.Sgf_game:
    """Create an SGF game object from a GameResult.

    This function converts self-play game data into proper SGF format
    using the sgfmill library, including all relevant metadata.

    Parameters
    ----------
    game_result : GameResult
        The game result containing moves and outcome
    board_size : int
        Board size (default 19)
    komi : float
        Komi value (default 7.5)
    num_simulations : Optional[int]
        MCTS simulations per move (for metadata comment)
    temperature_threshold : Optional[int]
        Temperature threshold setting (for metadata comment)
    player_name : str
        Player name for both black and white (default "Light-Go Self-Play")

    Returns
    -------
    sgf.Sgf_game
        SGF game object ready to be serialized

    Examples
    --------
    >>> sgf_game = create_sgf_from_game_result(result, board_size=19, komi=7.5)
    >>> with open('game.sgf', 'wb') as f:
    ...     f.write(sgf_game.serialise())
    """
    # Create new SGF game
    game = sgf.Sgf_game(size=board_size)

    # Set root properties
    root = game.get_root()
    root.set("KM", komi)
    root.set("DT", datetime.now().strftime("%Y-%m-%d"))
    root.set("AP", ("Light-Go", "1.0"))
    root.set("PB", player_name)
    root.set("PW", player_name)
    root.set("RU", "Chinese")

    # Set game result
    if game_result.winner:
        # Calculate score if available (for now just mark as win)
        result_str = f"{'B' if game_result.winner == 'black' else 'W'}+"
        root.set("RE", result_str)

    # Add comment with MCTS settings
    comment_parts = ["Self-play game generated by Light-Go"]
    if num_simulations is not None:
        comment_parts.append(f"MCTS simulations: {num_simulations}")
    if temperature_threshold is not None:
        comment_parts.append(f"Temperature threshold: {temperature_threshold}")
    root.set("C", "\n".join(comment_parts))

    # Add moves to the game
    if game_result.moves:
        for move_data in game_result.moves:
            move_coords, color = move_data

            # Convert color format: 'b'/'w' -> 'b'/'w'
            sgf_color = color.lower()

            # Convert move coordinates
            if move_coords is None:
                # Pass move
                node = game.extend_main_sequence()
                node.set_move(sgf_color, None)
            else:
                row, col = move_coords
                # sgfmill uses (row, col) format directly
                node = game.extend_main_sequence()
                node.set_move(sgf_color, (row, col))

    return game


def generate_sgf_filename(
    game_index: int,
    winner: Optional[str],
    num_moves: int,
    worker_id: int = 0,
    timestamp: Optional[str] = None,
    score: Optional[float] = None
) -> str:
    """Generate a standardized SGF filename.

    Format: selfplay_YYYYMMDD_HHMMSS_worker{id}_game{num:04d}_{outcome}.sgf

    Parameters
    ----------
    game_index : int
        Game number/index
    winner : Optional[str]
        Winner color ('black', 'white', or None)
    num_moves : int
        Number of moves in the game
    worker_id : int
        Worker identifier for parallel execution (default 0)
    timestamp : Optional[str]
        Timestamp string (default: current time in YYYYMMDD_HHMMSS format)
    score : Optional[float]
        Winning margin if known

    Returns
    -------
    str
        Standardized filename

    Examples
    --------
    >>> generate_sgf_filename(42, 'black', 250, worker_id=0)
    'selfplay_20260116_143025_worker0_game0042_B+.sgf'
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Format outcome
    if winner is None:
        outcome = "Draw"
    else:
        outcome_color = 'B' if winner == 'black' else 'W'
        if score is not None:
            outcome = f"{outcome_color}+{score:.1f}"
        else:
            outcome = f"{outcome_color}+"

    # Build filename
    filename = f"selfplay_{timestamp}_worker{worker_id}_game{game_index:04d}_{outcome}.sgf"

    return filename


def save_game_result_to_sgf(
    game_result: GameResult,
    output_dir: str,
    game_index: int = 0,
    worker_id: int = 0,
    board_size: int = 19,
    komi: float = 7.5,
    num_simulations: Optional[int] = None,
    temperature_threshold: Optional[int] = None,
    score: Optional[float] = None
) -> str:
    """High-level function to save a GameResult as an SGF file.

    This function combines filename generation, SGF creation, and file saving
    into a single convenient call. It automatically creates the output directory
    if it doesn't exist.

    Parameters
    ----------
    game_result : GameResult
        The game result to save
    output_dir : str
        Directory to save the SGF file
    game_index : int
        Game number/index (default 0)
    worker_id : int
        Worker identifier (default 0)
    board_size : int
        Board size (default 19)
    komi : float
        Komi value (default 7.5)
    num_simulations : Optional[int]
        MCTS simulations per move
    temperature_threshold : Optional[int]
        Temperature threshold setting
    score : Optional[float]
        Winning margin if known

    Returns
    -------
    str
        Path to the saved SGF file

    Raises
    ------
    OSError
        If directory creation or file writing fails

    Examples
    --------
    >>> path = save_game_result_to_sgf(
    ...     result,
    ...     output_dir='data/sgf/selfplay',
    ...     game_index=0,
    ...     board_size=19,
    ...     komi=7.5
    ... )
    >>> print(f"Saved to: {path}")
    """
    # Create output directory if it doesn't exist
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Generate timestamp once for consistency
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Generate filename
    filename = generate_sgf_filename(
        game_index=game_index,
        winner=game_result.winner,
        num_moves=game_result.num_moves,
        worker_id=worker_id,
        timestamp=timestamp,
        score=score
    )

    # Create SGF game object
    sgf_game = create_sgf_from_game_result(
        game_result=game_result,
        board_size=board_size,
        komi=komi,
        num_simulations=num_simulations,
        temperature_threshold=temperature_threshold
    )

    # Save to file
    file_path = output_path / filename
    with open(file_path, 'wb') as f:
        f.write(sgf_game.serialise())

    logger.debug(f"SGF saved to: {file_path}")

    return str(file_path)
