name: Engine Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: py-actions/py-dependency-install@v4
        with:
          path: requirements.txt
      - name: Install pip and pytest
        run: |
          python -m pip install --upgrade pip pytest
      - name: Run Engine unit tests
        run: pytest tests/unit_tests/engine.py
