name: Full Pipeline Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest
          pip install -r requirements.txt
      - name: Run REST API integration tests
        run: pytest tests/integration/test_rest_api.py
      - name: Run end-to-end tests
        run: pytest tests/e2e/test_full_pipeline.py
