name: Health Check Tests

on:
  push:
    paths:
      - 'monitoring/health_check.py'
      - 'tests/unit/test_health_check.py'
      - '.github/workflows/health_check.yml'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'monitoring/health_check.py'
      - 'tests/unit/test_health_check.py'
      - '.github/workflows/health_check.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip and pytest
        run: |
          python -m pip install --upgrade pip pytest
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run health check unit tests
        run: pytest tests/unit/test_health_check.py
