name: Performance Monitor Tests

on:
  pull_request:
    paths:
      - 'monitoring/performance.py'
      - 'tests/performance/test_performance.py'
      - '.github/workflows/performance.yml'
  push:
    branches: [main]
    paths:
      - 'monitoring/performance.py'
      - 'tests/performance/test_performance.py'
      - '.github/workflows/performance.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip and pytest
        run: |
          python -m pip install --upgrade pip pytest
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Performance unit tests
        run: pytest tests/performance/test_performance.py
