name: SGF to Input Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: py-actions/py-dependency-install@v4
        with:
          path: requirements.txt
      - name: Install pip and pytest
        run: |
          python -m pip install --upgrade pip pytest
      - name: Run tests
        uses: pytest-dev/pytest-action@v2
        with:
          args: tests/unit_tests/test_sgf_to_input.py

