name: WebSocket API Tests

on:
  pull_request:
    paths:
      - 'api/websocket_api.py'
      - 'tests/unit_tests/test_websocket_api.py'
  push:
    branches: [main]
    paths:
      - 'api/websocket_api.py'
      - 'tests/unit_tests/test_websocket_api.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip and pytest
        run: |
          python -m pip install --upgrade pip pytest
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run WebSocket API unit tests
        run: pytest tests/unit_tests/test_websocket_api.py
